### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by MSchaming** [MSchaming/JS-NumberGuessingGame#1]
## Left to do ##

- [ ] add README.md
- [x] build out tracker for incorrect guesses
- [x] change submit button text to say "Play Again"
- [x] create event to reload page
